services:
  php:
    build: 
      context: './'
      dockerfile: Dockerfile-php
    container_name: php_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/var/www/html
    links:
      - db

  db:
    build: 
      context: './'
      dockerfile: Dockerfile-mysql
    container_name: mysql_server
    volumes:
      - /var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    